

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace gzsw.model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class gzswEntities : DbContext
{
    public gzswEntities()
        : base("name=gzswEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<SYS_LOG> SYS_LOG { get; set; }

    public virtual DbSet<SYS_ROLEFUNCTION> SYS_ROLEFUNCTION { get; set; }

    public virtual DbSet<SYS_USER> SYS_USER { get; set; }

    public virtual DbSet<SYS_USEROLE> SYS_USEROLE { get; set; }

    public virtual DbSet<SYS_FUNCTION> SYS_FUNCTION { get; set; }

    public virtual DbSet<SYS_MENU> SYS_MENU { get; set; }

    public virtual DbSet<SYS_LOGINLOG> SYS_LOGINLOG { get; set; }

    public virtual DbSet<SYS_ORGANIZE> SYS_ORGANIZE { get; set; }

    public virtual DbSet<SYS_ROLE> SYS_ROLE { get; set; }

    public virtual DbSet<SYS_USERORGANIZE> SYS_USERORGANIZE { get; set; }

    public virtual DbSet<CHK_COUNTER> CHK_COUNTER { get; set; }

    public virtual DbSet<CHK_STAFFCHK_EVENT> CHK_STAFFCHK_EVENT { get; set; }

    public virtual DbSet<CLI_CLIENTEVENT> CLI_CLIENTEVENT { get; set; }

    public virtual DbSet<CLI_COUNTERSTATE> CLI_COUNTERSTATE { get; set; }

    public virtual DbSet<STAT_DAYHYYWTJ> STAT_DAYHYYWTJ { get; set; }

    public virtual DbSet<STAT_DAYQUEUETJ> STAT_DAYQUEUETJ { get; set; }

    public virtual DbSet<STAT_DAYYWTJ> STAT_DAYYWTJ { get; set; }

    public virtual DbSet<SYS_COUNTER> SYS_COUNTER { get; set; }

    public virtual DbSet<SYS_CURRQUEUEHIST> SYS_CURRQUEUEHIST { get; set; }

    public virtual DbSet<SYS_CURRYWHIST> SYS_CURRYWHIST { get; set; }

    public virtual DbSet<SYS_DETAILSERIAL> SYS_DETAILSERIAL { get; set; }

    public virtual DbSet<SYS_HALL> SYS_HALL { get; set; }

    public virtual DbSet<SYS_NSRHY> SYS_NSRHY { get; set; }

    public virtual DbSet<SYS_QUEUEHIST> SYS_QUEUEHIST { get; set; }

    public virtual DbSet<SYS_QUEUEING> SYS_QUEUEING { get; set; }

    public virtual DbSet<SYS_QUEUESERIAL> SYS_QUEUESERIAL { get; set; }

    public virtual DbSet<SYS_STAFF> SYS_STAFF { get; set; }

    public virtual DbSet<SYS_STAFFBUSI> SYS_STAFFBUSI { get; set; }

    public virtual DbSet<SYS_TICKETQUEUESERIAL> SYS_TICKETQUEUESERIAL { get; set; }

    public virtual DbSet<SYS_YWHIST> SYS_YWHIST { get; set; }

    public virtual DbSet<SYS_DLSERIAL> SYS_DLSERIAL { get; set; }

    public virtual DbSet<SYS_NSRINFO> SYS_NSRINFO { get; set; }

}

}

